### ISSUE TITLE
Editorconfig is failing svg images with line-length rules

### ISSUE THREAD

**Issue by jobackman** [tobiipro/support-firecloud#120]
We were adding some svg files to the image assets when we noted that our editorconfig will stop pushes because the svg files exceed the allowed line-length. 

I would assume images should be excluded from being linted by editorconfig. 

I would suggest excluding svg files from the editorconfig either entirely, or at least by this rule:

```editorconfig
[*.svg]
max_line_length = none
```

Thoughts?

**Comment by andreineculau** [comment]
replying inline to separate concerns

> I would assume images should be excluded from being linted by editorconfig.

editorconfig per se doesn't distinguish between binary and text files, so it's true that we could add definitions like

```
[*.{gif,png,jpg,jpeg,zip,etc,etc,etc}]
insert_final_newline = none
max_line_length = none
etc = none
```

on the other hand, the tool that we use to lint files based on the editorconfig configuration excludes binary files starting with version 2.0.0 https://github.com/jedmao/eclint/blob/master/CHANGELOG.md

so it is a bit redundant in that sense

> I would suggest excluding svg files from the editorconfig either entirely, or at least by this rule:

SVG files are not binary, they are just XML, like HTML files are. I don't see why they should be special and ignored by editorconfig.

Since you're not writing these SVGs by hand, and just importing them as assets, I suggest adding the `src/assets` (or similar) path to the SF_VENDOR_FILES_IGNORE variable in Makefile.

**Comment by jobackman** [comment]
> Since you're not writing these SVGs by hand, and just importing them as assets, I suggest adding the src/assets (or similar) path to the SF_VENDOR_FILES_IGNORE variable in Makefile.

Ahaa! Didnt know about _SF_VENDOR_FILES_IGNORE_. It looks like it solved our issues, so I'll close this! 

Thanks 🙏
