### ISSUE TITLE
Install erlang on bootstrap?

### ISSUE THREAD

**Issue by IanSavchenko** [tobiipro/support-firecloud#122]
@afogelberg approached me today with katt not being able to fetch deps. It appeared that he didn't have `erlang` on his machine. Should this maybe be a part of bootstrap?

**Comment by andreineculau** [comment]
Thanks for bringing this up, Ian!
Erlang is not part of the current bootstrap because it's not a generic tool (i.e. gnu tools) nor is it a tool used by most of our repos. Plus it was taking a while to compile - but should be fast now with the linuxbrew setup. Saying this from the CI bootstrap's perspective.

I think what should happen is that `make deps` should actually run `Brewfile.inc.sh`, if one exists in the repo. It's just that it should be "smart" 🤦‍♂ and skip everything that is already part of the dev bootstrap.

**Comment by andreineculau** [comment]
fixed via https://github.com/tobiipro/support-firecloud/commit/1f84db26a5b43b6ce882200d43cefa21985a2ef1 and update docs https://github.com/tobiipro/support-firecloud/commit/5354492b7198866e4defcfb54ce80700d78aaf87

just need to update support-firecloud everywhere now :(
